# Generated by Django 4.1.1 on 2022-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rename_discription_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='info',
            field=models.TextField(help_text='About you...', max_length=200, null=True, verbose_name='authors_info'),
        ),
    ]
