# Generated by Django 4.1.1 on 2022-09-19 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_author_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['publish_date']},
        ),
        migrations.AddField(
            model_name='comment',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 17, 29, 50, 957244), verbose_name='pubdate'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(default=datetime.datetime(2022, 9, 19, 17, 29, 50, 957244), verbose_name='pubdate'),
        ),
    ]
